### ISSUE TITLE
The SCTtransform function normalized denoised gene expression data ?

### ISSUE THREAD

**Issue by zhangqi234** [yunguan-wang/SPROD#31]
Thanks for your software. I have some questions about the analysis process.

1.For gene expression data from sprod_Denoised_matrix.txt, could I use the SCTtransform function in seurat to normalize my data?
2.If I have six samples, I should integrate the denoised gene expression data to remove batch effect?

**Comment by ice4prince** [comment]
Hi Zhangqi234, thank you for you questions:
1. the de-noised data is normalized, so a further normalization is not needed. However, if you insist, you can.
2. Batch correction CAN be completed before or after Sprod. **NOTE**: but DO NOT input integrated gene expression data to Sprod, because the position information of different samples may conflict which will result in incorrect de-noising.

**Comment by zhangqi234** [comment]
Thanks for your answer very much. This is very helpful for me. But I have another question.
1. If I conducted Sprod analysis after batch correction ,  Can the gene expression of different samples be directly compared? 
2. Should I adjust the order of Sprod analysis and batch correction?

**Comment by yunguan-wang** [comment]
Hi @zhangqi234, thank for your questions.
1. Your first question is more on the batch correction method side. The short answer is it depends on what methods you are using. If the data from batch correction can be directly used in differential analysis, then yes, otherwise probably not.  Most batch correction methods will distort the expression data and thus it is usually not a good idea to run differential analysis using batch corrected data. 
2. I suggest run sprod first on each individual batch, then perform the batch correction.

**Comment by zhangqi234** [comment]
Thanks for your answer very much. This is very very helpful for me.
